title: Conall Doherty # your name (or website title) here
logo: "https://media-exp1.licdn.com/dms/image/C4D03AQFsEWL0Y3eQTg/profile-displayphoto-shrink_200_200/0?e=1586390400&v=beta&t=T1kV7X6VU3X6UuS6K-VGUHwtOB7BrbzuSgl5-O_4OdI" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Former Data Analyst intern in Irish Life and recent Data Science graduate from Univerty College Dublin. 
  My experience revolves around applied statistics, machine learning, research science and software engineering 
  <br><br>
  <a href="https://www.linkedin.com/in/conall-doherty/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
